apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: 'true'
    include.release.openshift.io/self-managed-high-availability: 'true'
    include.release.openshift.io/single-node-developer: 'true'
    oauth-apiserver.openshift.io/secure-token-storage: 'true'
    release.openshift.io/create-only: 'true'
    argocd.argoproj.io/sync-wave: "1"
  name: cluster
  ownerReferences:
    - apiVersion: config.openshift.io/v1
      kind: ClusterVersion
      name: version
      uid: 1a7b14da-0aba-4fd8-a642-1a4b1a0f64c6
spec:
  audit:
    profile: Default
  servingCerts:
    namedCertificates:
    - names:
      - api.okd.homie.estate
      servingCertificate:
        name: okd-api-cert