apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  namespace: openshift-ingress-operator
spec:
  clientTLS:
    clientCA:
      name: ''
    clientCertificatePolicy: ''
  endpointPublishingStrategy:
    type: HostNetwork
    hostNetwork:
      httpPort: 8080
      httpsPort: 8443
      statsPort: 1936
  defaultCertificate:
    name: default-ingress-wildcard-cert
  httpCompression: {}
  routeSelector:
    matchExpressions:
    - key: type
      operator: NotIn
      values:
      - internal
  logging:
    access:
      destination:
        type: Container
      logEmptyRequests: Log
  httpEmptyRequestsPolicy: Respond
  httpErrorCodePages:
    name: ''
  replicas: 1
  tuningOptions: {}
  unsupportedConfigOverrides: null
