apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    issuer-env: prod
    solver: cloudflare
  name: internal-ingress-wildcard
  namespace: openshift-ingress
spec:
  dnsNames:
    - '*.apps.internal.okd.homie.estate'
  duration: 2160h0m0s
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  renewBefore: 360h0m0s
  secretName: internal-ingress-wildcard-cert
  subject:
    organizations:
      - Homies
  usages:
    - digital signature
    - key encipherment
