apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: 'true'
    include.release.openshift.io/self-managed-high-availability: 'true'
    include.release.openshift.io/single-node-developer: 'true'
    release.openshift.io/create-only: 'true'
    argocd.argoproj.io/sync-wave: "1"
  name: cluster
spec:
  identityProviders:
    - github:
        clientID: e6936d0951a98ee7dfaa
        clientSecret:
          name: github-secret
        organizations:
          - homie-estate
      mappingMethod: claim
      name: GitHub
      type: GitHub
