apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/intel-device-plugins-operator.intel-device-plugins-operator: ''
  name: intel-device-plugins-operator
  namespace: intel-device-plugins-operator
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: intel-device-plugins-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace
