apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: benhwebster@gmail.com
    preferredChain: ''
    privateKeySecretRef:
      name: letsencrypt-staging-issuer-account-key
    server: 'https://acme-staging-v02.api.letsencrypt.org/directory'
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              key: api-token
              name: cloudflare-api-token-secret
        selector:
          dnsZones:
            - homie.estate
          matchLabels:
            issuer-env: prod
            solver: cloudflare
