apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/benhwebster/cluster-configs
      revision: main
      directories:
      - path: homelab-okd/apps/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: apps
      syncPolicy:
#        automated:
#          prune: true
#          selfHeal: true
        retry:
          limit: 15
          backoff:
            duration: 15s
            factor: 2
            maxDuration: 5m
      source:
        repoURL: https://github.com/benhwebster/cluster-configs
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
