replicaCount: 3
extraArgs:
  - --autogenInternals=false
  - --clientRateLimitQPS=30
  - --clientRateLimitBurst=60
serviceMonitor:
  enabled: true
topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        app.kubernetes.io/instance: kyverno
securityContext: null