---
global:
  nameOverride: uptime-kuma
image:
  repository: uptime-kuma-container-image
  pullPolicy: IfNotPresent
env:
  TZ: America/New_York
service:
  main:
    enabled: true
    type: ClusterIP
    ports:
      http:
        protocol: TCP
        port: 80
        targetPort: 3001
ingress:
  main:
    enabled: false
persistence:
  data:
    enabled: true
    storageClass: ssd
    accessMode: ReadWriteMany
    size: 4Gi
