kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'csi-nfs-privileged'
subjects:
  - kind: ServiceAccount
    name: csi-nfs-controller-sa
    namespace: csi-driver-nfs
  - kind: ServiceAccount
    name: csi-nfs-node-sa
    namespace: csi-driver-nfs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:privileged'
