apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: csi-driver-nfs
  repo:  https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
  releaseName: csi-driver-nfs
  namespace: csi-driver-nfs
  valuesFile: values.yaml
  version: 4.6.0
resources:
- namespace.yaml
- clusterrolebinding.yaml
- storageclass.yaml