kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/gdeedler/aram-api'
    openshift.io/generated-by: OpenShiftWebConsole
  name: aram-api
  namespace: aram-machine
  labels:
    app: aram-api
    app.kubernetes.io/component: aram-api
    app.kubernetes.io/instance: aram-api
    app.kubernetes.io/name: aram-api
    app.kubernetes.io/part-of: aram-machine-backend
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 16-ubi8
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'aram-api:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'nodejs:16-ubi8'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/benhwebster/aram-api/'
      ref: nomongo
    contextDir: /
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: aram-api-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: aram-api-github-webhook-secret
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
  runPolicy: Serial
