kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: main
    app.openshift.io/vcs-uri: 'https://github.com/gdeedler/aram-machine'
    openshift.io/generated-by: OpenShiftWebConsole
  name: aram-machine
  namespace: aram-machine
  labels:
    app: aram-machine
    app.kubernetes.io/component: aram-machine
    app.kubernetes.io/instance: aram-machine
    app.kubernetes.io/name: aram-machine
    app.kubernetes.io/part-of: aram-machine-frontend
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 16-ubi8
spec:
  lookupPolicy:
    local: false