kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres
  namespace: aram-machine
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: syno
  volumeMode: Filesystem